name: JAVA CI
on: push
jobs:
  Clone-down:
    name: Clone down repo
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
    - uses: actions/checkout@v2
    - name: Upload Repo
      uses: actions/upload-artifact@v2
      with:
        name: code
        path: .
  Build:
      runs-on: ubuntu-latest
      needs: Clone-down
      container: gradle:6-jdk11
      steps:
      - name: Download code
        uses: actions/download-artifact@v2
        with: 
          name: code
          path: .
      - name: Build with Gradle
        run: chmod +x ci/build-app.sh && ci/build-app.sh
      - name: Test with Gradle
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with: 
          name: code
          path: .

#A line-by-line explanation of the above:

#Line 1: The name attribute provides useful organizational information when returning warnings, errors, and output. The name should be meaningful to you as an action within your build process.
#Line 2: The on is the name of the GitHub event that triggers the workflow.
#Line 3: The jobs level contains a collection of jobs that make up the workflow.
#ine 4-5: The my-job is an example of the name for a job, runs-on describes on which operating system the pipeline should run.
#ine 6-8: The steps collection is an ordered list of run directives. Each run directive is executed in the order in which it is declared.